### ISSUE TITLE
still no working in local instance ubuntu 32 bits

### ISSUE THREAD

**Issue by johnfelipe** [leonrch/SpeechToSpeech#6]
sudo nano /home/felipe/SpeechToSpeech/.env
## 

{
   "speech_to_text": [
      {
         "name": "speech-to-text-service-standard",
         "label": "speech_to_text",
         "plan": "standard",
         "credentials": {
            "url": "https://stream.watsonplatform.net/speech-to-text/api",
            "password": "mypass",
            "username": "265bdf48-47de-4bd0-8a9c-05194f2f29dd"
         }
      }
   ],
   "language_translation": [
      {
         "name": "language-translation-service",
         "label": "language_translation",
         "plan": "standard",
         "credentials": {
            "url": "https://gateway.watsonplatform.net/language-translation/api",
            "password": "mypass",
            "username": "bf0d3db6-ceae-4d9a-8c99-f581d5a22dab"
         }
      }
   ],
   "text_to_speech": [
      {
         "name": "text-to-speech-service",
         "label": "text_to_speech",
         "plan": "standard",
         "credentials": {
            "url": "https://stream.watsonplatform.net/text-to-speech/api",
            "password": "mypass",
            "username": "0ddf28b9-677b-4bb2-b6d3-51f8dfc547ff"
         }
      }
   ]
}
## 

http://181.135.63.86:3006/
Not working

**Comment by leonrch** [comment]
The STT service requires you to get authentication token first and then use
it. The attached screen shot is a good evidence you are not doing that.

[image: Inline image 1]
Using call stack (for failing methods) can be very helpful:

[image: Inline image 2]
as it immediately brings you to the problematic code (use Chrome for
debugging).

[image: Inline image 3]

The application works fine if you deploy it using the magic button "Deploy
on Bluemix", which means the source code is OK so as the used credentials.
Once again, I do not think I deserved the honour to debug YOUR changes in
my application. Please try to make as fewer changes in the code as possible
and ALWAYS check if it is working even after the simplest, smallest change !

**Comment by johnfelipe** [comment]
i havent any change in your code, then put in description, ONLY WORKS MAGIC BUTTON, because in local instance not work

**Comment by leonrch** [comment]
How do you think this application was developed? Of course, it does work
locally. We are using 64 - bit operating systems. For example, I am able to
run the application locally on 64-bit Windows.
Try to use 64-bit system.

**Comment by johnfelipe** [comment]
`/SpeechToSpeech/.env` is good setted?

**Comment by johnfelipe** [comment]
Linux ubuntu-1gb-nyc3-01 3.13.0-85-generic #129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

64 bits digitalocean instance

only edit credentials nothing more

http://104.131.189.60:3000/

and

still not working

**Comment by johnfelipe** [comment]
pls share me instructions for run application
tnks

**Comment by johnfelipe** [comment]
![notwork](https://cloud.githubusercontent.com/assets/428820/16020192/63c6c976-3172-11e6-8881-747aa7606ea5.png)

**Comment by leonrch** [comment]
The STT part seems to be working correctly. However, in your version I see
the list of languages is different from the one my application is using.

My code shows:

[image: Inline image 1]

Your code shows:

[image: Inline image 2]
It is IMPORTANT for your application to show the source languages
EXACTLY as they are shown by my application. Otherwise, no target language
can be selected.
Look at public/js/main.js, lines 260 - 320 for more details.

**Comment by johnfelipe** [comment]
i cant see your images, pls reupload

**Comment by johnfelipe** [comment]
Pls re upload

My code shows:

**[image: Inline image 1]**

Your code shows:

**[image: Inline image 2]**

**Comment by johnfelipe** [comment]
Hi mate, pls upload again images for compare...

**Comment by johnfelipe** [comment]
hi me again, sorry, but i request upload again images for compare
